name: corpus
# or corpus_analyze?
description: This is a tool to calculate the API usage for a package.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^3.4.1
  args: ^2.0.0
  cli_util: ^0.3.0
  http: ^0.13.0
  path: ^1.8.0
  surveyor:
    git:
      url: https://github.com/pq/surveyor

dev_dependencies:
  checks:
    git:
      url: https://github.com/dart-lang/test
      path: pkgs/checks
  lints: '>=1.0.0 <3.0.0'
  test: ^1.16.0
  test_descriptor: ^2.0.0
